name: Deploy to prod

# Trigger after successful deployment to dev environment
on:
  release:
    types:
      - "published"
  workflow_dispatch:

jobs:
  terraform:
    name: "Deploy to prod"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: "echo hello; ls -alt"
